mauvais_code/src/Entity/PostsBlog.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostsBlogRepository")
 */
class PostsBlog
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="text")
     */
    private $Content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $CreatedAt;

    public function getId()
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(?\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }
}

mauvais_code/src/Controller/ShowBlogsController.php
<?php

namespace App\Controller;

use App\Repository\PostsBlogRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;


class ShowBlogsController extends Controller
{

    //MAUVAISE PRATIQUE : utilisation des annotations
    /**
     * @Route("/", name="show_all_articles")
     */
    public function index(PostsBlogRepository $post_blog_repository)
    {

        $allposts = $post_blog_repository->findAll();  //MAUVAISE PRATIQUE : utilisation direct de methode repository

        return $this->render('show_blogs/index.html.twig', [
            'posts' => $allposts,
        ]);
    }


    /**
     * @Route("article/{id}", name="show_article")
     */
    public function articleById (Request $request, PostsBlogRepository $post_blog_repository, $id)
    {
        $post = $post_blog_repository->find($id);

        //MAUVAISE PRATIQUE : aucune utilisation de validation

        return $this->render('show_blogs/index.html.twig', [
            'posts' => $post,
        ]);
    }

    /**
     * @Route("/article/{author}/id/{id}", name="show_article_author")
     */
    //MAUVAISE PRATIQUE : trop de passage de paramatres
    public function articleByIdAndAuthor (Request $request, PostsBlogRepository $post_blog_repository, $author, $id)
    {
        if (isset($author))
        {
            if (isset($id)) //MAUVAISE PRATIQUE : le code peut se réduire à une seule condition, un seul if
            {
                $allposts = $post_blog_repository->findBy(
                    ['name' => 'Keyboard'],
                    array('price' => 'ASC')
                );

                return $this->render('show_blogs/index.html.twig', [
                    'posts' => $allposts,
                ]);
            }
        }

        return $this->render('error.html.twig');

    }

    //Side note MAUVAISE PRATIQUE : utilisation de traits, replique de codes


    /**
     * @Route("/edit-article/id/{id}", name="show_article")
     */
    public function editArticle (PostsBlogRepository $post_blog_repository, ObjectManager $manager, $id)
    {
        //...

    }
}

mauvais_code/templates/error.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Error!</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
    <h4>There is an error !</h4>
    </body>
</html>

mauvais_code/templates/show_blogs/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des posts!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Liste des articles postés sur le blog :</h1>

    {%  for post in posts %}

        <div class="article" >

            <h3>{{ post.title }}</h3>
            <textarea width="300" height="200" contenteditable="false">{{ post.content }}</textarea>
            <p>{{ post.author }} - {{ post.createdAt }}</p>

        </div>


    {% endfor %}
</div>
{% endblock %}